INSERT INTO `anggota` (`id`, `nama_anggota`, `status`, `nama_jabatan`, `instagram`, `image_link`, `satuan_id`, `created_at`, `updated_at`) VALUES
	(1, 'Mahiza Aidan', 'BPH', 'Kepala Biro', NULL, 'Anggota/3/Mahiza Aidan.jpg', 3, '2024-06-20 14:46:38', '2024-06-29 04:38:45'),
	(2, 'Ilham Rafi Prathama', 'BPH', 'Kepala Bagian Redaksi Publikasi', NULL, 'Anggota/3/Ilham Rafi Prathama.jpg', 3, '2024-06-29 04:40:30', '2024-06-29 04:40:30'),
	(3, 'Aisha Djody Shanata', 'BPH', 'Kepala Bagian Media Informasi', NULL, 'Anggota/3/Aisha Djody Shanata.jpg', 3, '2024-06-29 04:41:10', '2024-06-29 04:41:10'),
	(4, 'Rosalia Sanika S.', 'BPH', 'Kepala Bagian Media Kreatif', NULL, 'Anggota/3/Rosalia Sanika Satyawada.jpg', 3, '2024-06-29 04:41:46', '2024-06-29 04:41:46'),
	(5, 'Cindy Veronika Situmorang', 'STAF', 'Staf Ahli', 'chindyvrnk', 'Anggota/3/Chindy Veronika Situmorang.jpg', 3, '2024-06-29 05:36:05', '2024-06-29 05:36:05'),
	(6, 'Cinta Ayu Amelia', 'STAF', 'Staf Ahli', 'cintaayuua', 'Anggota/3/Cinta Ayu Amelia.jpg', 3, '2024-06-29 05:37:09', '2024-06-29 05:37:09'),
	(7, 'Dian Cahyaning Putri', 'STAF', 'Staf Ahli', 'diiannp_', 'Anggota/3/Dian Cahyaning Putri.jpg', 3, '2024-06-29 05:37:46', '2024-06-29 05:37:46'),
	(8, 'Fiqi Nadhratul \'Ulya', 'STAF', 'Staf Ahli', 'fiqibu', 'Anggota/3/Fiqi Nadhratul \'Ulya.jpg', 3, '2024-06-29 05:38:20', '2024-06-29 05:38:20'),
	(9, 'Ruth Gabriella Manik', 'STAF', 'Staf Ahli', 'ruthgabriella_m', 'Anggota/3/Fiqi Nadhratul \'Ulya.jpg', 3, '2024-06-29 05:57:00', '2024-06-29 05:57:00');

INSERT INTO `satuan` (`id`, `slug`, `satuan`, `nama_satuan`, `deskripsi`, `updated_at`, `created_at`) VALUES
	(2, 'PAO', 'BIRO', 'PEMBERDAYAAN APARATUR ORGANISASI', 'Biro Pemberdayaan Aparatur Organisasi bertanggung jawab secara keseluruhan mengenai internalisasi BEM FISIP UB. Aktif untuk memberdayakan sumber daya manusia yang disebut sebagai aparatur organisasi yang berlandaskan kepada visi, misi, dan nilai melalui', '2024-06-29 03:06:29', '2024-06-06 02:38:55'),
	(3, 'PUSKOMINFO', 'BIRO', 'PUSAT KOMUNIKASI, MEDIA & INFORMASI', 'Biro Pusat Komunikasi dan Informasi bertanggung jawab atas pengelolaan seluruh media sosial yang dimiliki BEM FISIP UB dalam mempublikasikan informasi yang berkaitan dengan FISIP UB kepada khalayak ramai melalui media yang kreatif, inovatif, dan kekinian,', '2024-06-29 03:09:39', '2024-06-06 02:40:12'),
	(6, 'ADKES', 'BIRO', 'ADMINISTRASI KESEKRETARIATAN', 'Biro Administrasi Kesekretariatan bertanggung jawab atas seluruh administrasi organisasi seperti pengelolaan surat menyurat, laporan, inventarisasi, tata usaha, dan sebagainya serta bertanggung jawab sebagai penunjang administrasi dalam program kerja dan', '2024-06-29 03:09:59', '2024-06-06 03:28:47'),
	(7, 'ADKEU', 'BIRO', 'ADMINISTRASI KEUANGAN', 'Biro Administrasi Keuangan bertanggung jawab untuk menjadi pengelola sumber daya keuangan lembaga dengan integritas, transparansi, dan akuntabilitas guna menjamin kelangsungan program kerja BEM FISIP UB pada aspek keuangan secara sehat dan bertanggung jawab.', '2024-06-29 03:13:00', '2024-06-06 03:29:28'),
	(8, 'ADVOKESMA', 'KEMENTERIAN', 'ADVOKASI DAN KESEJAHTERAAN MAHASISWA', 'Kementerian Advokasi dan Kesejahteraan Mahasiswa merupakan kementerian yang bertanggung jawab atas upaya advokasi dan kesejahteraan mahasiswa sebagai penjembatan antara mahasiswa dengan pihak dekanat terkait akademik, keuangan, dan kemahasiswaan.', '2024-06-29 03:13:59', '2024-06-06 03:31:24'),
	(9, 'DAGRI', 'KEMENTERIAN', 'DALAM NEGERI', 'Kementerian Dalam Negeri memiliki tupoksi meningkatkan produktivitas dan menjaga inter-konektivitas antar-lembaga yang ada FISIP UB, baik LKM, LSO, dan Komunitas. Selain itu, Kementerian Dalam Negeri juga berperan sebagai fasilitator dalam pengadvokasian isu internal FISIP yang berkaitan dengan lembaga yang ada di FISIP UB.', '2024-06-29 03:15:06', '2024-06-06 03:31:38'),
	(10, 'LUGRI', 'KEMENTERIAN', 'LUAR NEGERI', 'Kementerian Luar Negeri berfokus untuk mendorong eskternalisasi lembaga, guna mewujudkan hubungan baik BEM FISIP UB 2024 dengan stakeholder eksternal pada lingkup intra maupun ekstra fakultas, serta menjadi corong informasi dan kajian pada lingkup isu internasional guna membangun citra lembaga yang progresif dan inklusif.', '2024-06-29 03:16:05', '2024-06-06 03:32:00'),
	(11, 'PSDM', 'KEMENTERIAN', 'PENGEMBANGAN SUMBER DAYA MANUSIA', 'Kementerian Pengembangan Sumber Daya Mahasiswa memiliki peran untuk menciptakan formula serta melaksanakan program kerja berbasis pengembangan kualitas sumber daya mahasiswa baik softskill maupun hardskill sebagai penunjang kehidupan kampus hingga pasca-kampus.', '2024-06-29 03:16:47', '2024-06-06 03:32:18'),
	(12, 'GENDER', 'KEMENTERIAN', 'PENGARUSUTAMAN GENDER', 'Kementerian Pengarusutamaan Gender bertanggung jawab atas terlaksananya kajian dan gerakan strategis berbasis gender baik dalam bentuk advokasi langsung maupun advokasi gerakan untuk mewujudkan iklim sosial masyarakat yang berkeadilan gender, inklusif, dan terbebas dari kekerasan seksual maupun perundungan.', '2024-06-29 03:29:18', '2024-06-06 03:32:33'),
	(13, 'INOYA', 'KEMENTERIAN', 'INOVASI DAN KARYA ', 'Kementerian Inovasi dan Karya memiliki tupoksi dalam mengembangkan kemampuan akademik dan meningkatkan minat serta bakat dalam ranah akademik mahasiswa FISIP UB. Selain itu, Kementerian Inovasi dan Karya juga memiliki tanggung jawab untuk mampu mengeksplorasi aspek prestatif dan intelektualitas mahasiswa  dengan basis keilmuan di FISIP UB.', '2024-06-29 03:17:35', '2024-06-06 03:32:58'),
	(14, 'KASTRAT', 'KEMENTERIAN', 'KAJIAN  DAN AKSI STRATEGIS', 'Kementerian Kajian dan Aksi Strategis memiliki tugas pokok untuk mengimplementasikan aktualisasi isu yang telah dikaji secara cermat guna diwujudkan dalam bentuk pempropagandaaan maupun aksi langsung sebagai daya tekan atas kebijakan stakeholder baik secara direct maupun indirect.', '2024-06-29 03:17:59', '2024-06-06 03:33:21'),
	(15, 'SOSLING', 'KEMENTERIAN', 'SOSIAL DAN LINGKUNGAN', 'Kementerian Sosial dan Lingkungan bertugas untuk mengaktualisasikan fungsi kajian, gerakan serta pengabdian pada lingkup isu sosial-lingkungan guna mewujudkan perbaikan kualitas kesejahteraan sosial, kelestarian lingkungan hidup, serta jiwa sosial mahasiswa FISIP UB.', '2024-06-29 03:18:26', '2024-06-06 03:33:37'),
	(16, 'SENORA', 'KEMENTERIAN', 'SENI DAN OLAHRAGA', 'Kementerian Ekonomi Kreatif memiliki tugas pokok untuk menjadi fasilitator mahasiswa dalam meningkatkan minat dan kemampuan berwirausaha pada sektor kreatif serta menjadi badan usaha utama dalam menyediakan produk kreatif guna profit operasional organisasi..', '2024-06-29 03:18:50', '2024-06-06 03:33:53'),
	(17, 'EKRAF', 'KEMENTERIAN', 'EKONOMI KREATIF', 'Bertujuan untuk memfasilitasi minat mahasiswa pada bidang eksplorasi seni dan keolahragaan baik dalam bentuk kompetisi, kajian isu, pendampingan perlombaan dan pementasan guna mendorong aspek kreativitas mahasiswa FISIP.', '2024-06-29 03:19:22', '2024-06-06 03:34:15');
